const assert = require("assert");
const W = require("../js/words.js");
const car = W.OBJECTS[0];
assert(W.checkSpelling(car, "es", " COCHE "));
assert(W.checkSpelling(W.OBJECTS[1], "es", "arbol"));
assert(W.checkSpelling(car, "ja", "kuruma") && W.checkSpelling(car, "ja", "くるま"));
assert(!W.checkSpelling(car, "en", "cart"));
const p = W.newProgress();
assert(!W.completeStep(p, "car", "en", "recognize"));
assert(!W.completeStep(p, "car", "en", "spell"));
assert(!W.isLearned(p, "car", "en"));
assert(W.completeStep(p, "car", "en", "sentence"));
assert(W.isLearned(p, "car", "en") && !W.isLearned(p, "car", "es"));
assert.strictEqual(p.score, W.POINTS_PER_WORD);
assert(!W.completeStep(p, "car", "en", "spell")); // no double points
assert.strictEqual(p.score, W.POINTS_PER_WORD);
assert(W.options(car, "en", W.seededRandom(1)).includes("car"));
const known = W.fromWords({ en: "Car", es: "x", ja: "y" }, "t");
assert.strictEqual(known.id, "car"); assert.strictEqual(known.thumb, "t");
const dyn = W.fromWords({ en: "Fire Hydrant", es: "boca de incendios", ja: "消火栓" }, "t");
assert.strictEqual(dyn.id, "x_fire_hydrant");
assert(W.checkSpelling(dyn, "ja", "消火栓") && W.checkSpelling(dyn, "es", "Boca de incendios"));
assert(!W.options(dyn, "es", W.seededRandom(2)).slice().sort().some((v, i, a) => v === a[i - 1]));
const p2 = W.newProgress(); ["recognize", "spell", "sentence"].forEach((s) => W.completeStep(p2, dyn.id, "es", s));
assert(W.isLearned(p2, dyn.id, "es"));
console.log("ok");
